# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from pickle import dumps

from PyQt5 import QtCore, QtWidgets
from socket import *

ans = []


class QuizForm(QtWidgets.QWidget):
    switch_window = QtCore.pyqtSignal(str, socket)

    def __init__(self, name, questions, client):
        super().__init__()
        self.group = QtWidgets.QButtonGroup()
        self.name = name
        self.questions = questions
        self.i = -1
        self.client = client
        self.answers = []
        self.widget = QtWidgets.QWidget(self)

        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.line = QtWidgets.QFrame(self.widget)

        self.formLayout_2 = QtWidgets.QFormLayout()
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.setupUI()

    def setupUI(self):
        self.setStyleSheet(
            """
            QPushButton {
                border-style: outset;
                border-radius: 0px;
                padding: 6px;
            }
            QPushButton:hover {
                background-color: #FF0000;
                border-style: inset;
            }
            QPushButton:pressed {
                background-color: #800000;
                border-style: inset;
            }
            """
        )

        self.verticalLayout.setContentsMargins(0, 0, 0, 0)

        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet(".QWidget{background-color: rgb(0, 0, 0);}")

        self.verticalLayout_2.setContentsMargins(9, 0, 0, 0)

        self.verticalLayout_3.setContentsMargins(-1, 15, -1, -1)

        self.formLayout_2.setContentsMargins(50, 35, 59, -1)

        # self.label_2.setStyleSheet("color: rgb(231, 231, 231);\n"
        #                             "font: 15pt \"Verdana\";")
        # self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)

        self.textEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit.setStyleSheet("QTextEdit {\n"
                                    "color: red;\n"
                                    "font: 30pt \"Verdana\";\n"
                                    "border: None;\n"
                                    "border-bottom-color: white;\n"
                                    "border-radius: 10px;\n"
                                    "padding: 0 8px;\n"
                                    "background: rgb(0,0,0);\n"
                                    "selection-background-color: darkgray;\n"
                                    "}")
        self.textEdit.setReadOnly(True)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEdit)

        self.progressBar.setObjectName("progressBar")
        self.progressBar.setMinimumSize(QtCore.QSize(0, 40))
        self.progressBar.setStyleSheet('''QProgressBar
                                        {
                                            border: 2px solid white;
                                            border-radius: 5px;
                                            text-align: center;
                                        }
                                        QProgressBar::chunk
                                        {
                                            background-color: #ff0000;
                                            width: 2.15px;
                                            margin: 0.5px;
                                        }''')
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.progressBar)

        self.radioButton.setObjectName("radioButton")
        self.radioButton.setMinimumSize(QtCore.QSize(0, 40))
        self.radioButton.setStyleSheet("QRadioButton::indicator::unchecked"
                                       "{"
                                       "width : 20px;"
                                       "height : 20px;"
                                       "}"
                                       "QRadioButton::indicator::checked"
                                       "{"
                                       "width : 25px;"
                                       "height : 25px;"
                                       "}"
                                       "QRadioButton"
                                       "{"
                                       "color : red;"
                                       "font: 24pt Verdana;"
                                       "}")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.radioButton)

        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.radioButton_2.setStyleSheet("QRadioButton::indicator::unchecked"
                                         "{"
                                         "width : 20px;"
                                         "height : 20px;"
                                         "}"
                                         "QRadioButton::indicator::checked"
                                         "{"
                                         "width : 25px;"
                                         "height : 25px;"
                                         "}"
                                         "QRadioButton"
                                         "{"
                                         "color : red;"
                                         "font: 24pt Verdana;"
                                         "}")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.radioButton_2)

        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.radioButton_3.setStyleSheet("QRadioButton::indicator::unchecked"
                                         "{"
                                         "width : 20px;"
                                         "height : 20px;"
                                         "}"
                                         "QRadioButton::indicator::checked"
                                         "{"
                                         "width : 25px;"
                                         "height : 25px;"
                                         "}"
                                         "QRadioButton"
                                         "{"
                                         "color : red;"
                                         "font: 24pt Verdana;"
                                         "}")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.radioButton_3)

        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_4.setMinimumSize(QtCore.QSize(0, 40))
        self.radioButton_4.setStyleSheet("QRadioButton::indicator::unchecked"
                                         "{"
                                         "width : 20px;"
                                         "height : 20px;"
                                         "}"
                                         "QRadioButton::indicator::checked"
                                         "{"
                                         "width : 25px;"
                                         "height : 25px;"
                                         "}"
                                         "QRadioButton"
                                         "{"
                                         "color : red;"
                                         "font: 24pt Verdana;"
                                         "}")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.radioButton_4)

        self.group.addButton(self.radioButton)
        self.group.addButton(self.radioButton_2)
        self.group.addButton(self.radioButton_3)
        self.group.addButton(self.radioButton_4)

        self.line.setStyleSheet("border: 2px solid white;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.line)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())

        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "font: 17pt \"Verdana\";\n"
                                      "border: 2px solid red;\n"
                                      "padding: 5px;\n"
                                      "border-radius: 3px;\n"
                                      "opacity: 200;\n"
                                      "")
        self.pushButton.setAutoDefault(True)
        self.pushButton.clicked.connect(self.nextQuestion)
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.pushButton)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(8, QtWidgets.QFormLayout.SpanningRole, spacerItem)

        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.verticalLayout_3.addLayout(self.formLayout_2)

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)

        self.horizontalLayout_3.addWidget(self.widget)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.nextQuestion()

    def retranslateUi(self, qno, ques, op1, op2, op3, op4):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Question " + str(qno + 1)))
        self.textEdit.setText(_translate("MainWindow", ques))
        self.radioButton_4.setText(_translate("MainWindow", op1))
        self.radioButton_3.setText(_translate("MainWindow", op2))
        self.radioButton.setText(_translate("MainWindow", op3))
        self.radioButton_2.setText(_translate("MainWindow", op4))
        self.pushButton.setText(_translate("MainWindow", "Next"))
        self.progressBar.setProperty("value", qno * 20)

    def quizClient(self):
        self.retranslateUi(self.i, self.questions[self.i][0], self.questions[self.i][1][0],
                           self.questions[self.i][1][1], self.questions[self.i][1][2], self.questions[self.i][1][3])
        # for i in range(5):
        #     self.retranslateUi(i, self.questions[i][0], self.questions[i][1][0], self.questions[i][1][1],
        #                        self.questions[i][1][2], self.questions[i][1][3])
        #     sleep(5)

    def nextQuestion(self):
        self.i += 1
        if self.radioButton.isChecked():
            ans.append(self.radioButton.text())
        if self.radioButton_2.isChecked():
            ans.append(self.radioButton_2.text())
        if self.radioButton_3.isChecked():
            ans.append(self.radioButton_3.text())
        if self.radioButton_4.isChecked():
            ans.append(self.radioButton_4.text())
        self.group.setExclusive(False)
        self.radioButton.setChecked(False)
        self.radioButton_2.setChecked(False)
        self.radioButton_3.setChecked(False)
        self.radioButton_4.setChecked(False)
        self.group.setExclusive(True)
        if self.i < 5:
            self.quizClient()
        else:
            self.client.send(dumps(ans))
            self.switch_window.emit(self.name, self.client)
