# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QWidget):
    def __init__(self):
        self.centralwidget = QtWidgets.QWidget(self)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.radioButton = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_3 = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_4 = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_2 = QtWidgets.QRadioButton(self.splitter)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.formLayout = QtWidgets.QFormLayout()
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(827, 514)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout.setObjectName("formLayout")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.progressBar)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.textEdit)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton.setObjectName("radioButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.splitter)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.horizontalLayout.addLayout(self.formLayout)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                         "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                         "type=\"text/css\">\n "
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Fira Sans Semi-Light\'; "
                                         "font-size:10pt; font-weight:400; font-style:normal;\">\n "
                                         "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; "
                                         "margin-left:0px; margin-right:0px; -qt-block-indent:0; "
                                         "text-indent:0px;\"><span style=\" "
                                         "font-size:20pt;\"></span></p></body></html>"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_4.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_3.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
